<a href="https://colab.research.google.com/github/Vaishnavi-Baiti/NASSCOM/blob/main/WEEK%202/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:

# Random sampling from a custom list
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)

# Setting a seed ensures reproducible random results
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())



Random Choices: [5 1 1 5 3]
Seeded Random Number: 0.3745401188473625


In [7]:
# -----------------------------------------------------------
# 🔹 9. INDEXING AND SLICING WITH ARRAYS
# -----------------------------------------------------------

# Create a sample 1D array
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)

# Access single elements by index
print("Element at index 0:", arr[0])        # 10
print("Element at last index:", arr[-1])    # 60



Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [8]:
# -----------------------------------------------------------
# 🔹 10B. BOOLEAN INDEXING
# -----------------------------------------------------------

arr = np.array([5, 10, 15, 20, 25, 30])

# Create a boolean mask for values > 15
mask = arr > 15
print("Boolean Mask:", mask)

# Use mask to filter elements
print("Values greater than 15:", arr[mask])  # [20, 25, 30]

# Combine conditions
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])  # [20, 30]

Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]


In [9]:
# -----------------------------------------------------------
# 🔹 1. ARRAY CREATION FUNCTIONS
# -----------------------------------------------------------

# arange(): Create range of numbers like Python's range()
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)


Array using arange: [0 2 4 6 8]


In [10]:
# linspace(): Create evenly spaced values between two limits
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)



Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [11]:

# linspace(): Create evenly spaced values between two limits
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)




Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [12]:
# reshape(): Change shape without changing data
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

# flatten(): Convert multi-dimensional array to 1D
print("Flattened version:", arr3.flatten())


Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [13]:
# -----------------------------------------------------------
# 🔹 2. AGGREGATE FUNCTIONS
# -----------------------------------------------------------

data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)



Original Data:
 [[5 8 9]
 [2 4 6]]


In [14]:

print("Sum of all elements:", np.sum(data))             # Total sum
print("Column-wise sum:", np.sum(data, axis=0))         # Sum along columns
print("Row-wise mean:", np.mean(data, axis=1))          # Average of each row
print("Max value:", np.max(data))                       # Maximum value



Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9


In [15]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))                       # Minimum value
print("Standard Deviation:", np.std(data))              # Spread of values



Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585


In [16]:
# -----------------------------------------------------------
# 🔹 3. SORTING AND SEARCHING
# -----------------------------------------------------------

a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)



Original Array: [3 1 7 2 9]


In [17]:
# Sort array values
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)

# Find indices where condition is True (value > 4)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])


Sorted Array: [1 2 3 7 9]
Indices where value > 4: (array([2, 4]),)
Values > 4: [7 9]


In [18]:
# -----------------------------------------------------------
# 🔹 4. BROADCASTING IN NUMPY
# -----------------------------------------------------------

# Broadcasting allows NumPy to perform operations between arrays of different shapes
A = np.array([[1, 2], [3, 4]])  # 2x2 matrix
B = np.array([10, 20])          # 1D array with 2 elements

print("Matrix A:\n", A)
print("Vector B:", B)


Matrix A:
 [[1 2]
 [3 4]]
Vector B: [10 20]


In [19]:
# B is broadcasted to each row of A
C = A + B
print("Broadcasted Addition Result:\n", C)

Broadcasted Addition Result:
 [[11 22]
 [13 24]]


In [20]:
# -----------------------------------------------------------
# 🔹 5. CONDITIONAL OPERATIONS
# -----------------------------------------------------------

nums = np.array([1, 2, 3, 4, 5])

# Create boolean mask for condition nums > 3
mask = nums > 3
print("Mask (nums > 3):", mask)



Mask (nums > 3): [False False False  True  True]
